export const SAVE_REQUEST = 'SAVE_REQUEST';
export const SAVE_FAILURE = 'SAVE_FAILURE';
export const PROJECT_NAME_SAVE_SUCCESS = 'PROJECT_NAME_SAVE_SUCCESS';
export const PROJECT_CATEGORY_SAVE_SUCCESS = 'PROJECT_CATEGORY_SAVE_SUCCESS';
export const PROJECT_CHANNEL_SAVE_SUCCESS = 'PROJECT_CHANNEL_SAVE_SUCCESS';
export const PROJECT_AUDIO_SAVE_SUCCESS = 'PROJECT_AUDIO_SAVE_SUCCESS';
export const PROJECT_IMAGE_SAVE_SUCCESS = 'PROJECT_IMAGE_SAVE_SUCCESS';
export const PROJECT_FINISHED_SUCCESS = 'PROJECT_FINISHED_SUCCESS';
