export const SAVE_REQUEST = 'SAVE_REQUEST';
export const SAVE_FAILURE = 'SAVE_FAILURE';
export const PROJECT_NAME_SAVE_SUCCESS = 'PROJECT_NAME_SAVE_SUCCESS';
export const PROJECT_CATEGORY_SAVE_SUCCESS = 'PROJECT_CATEGORY_SAVE_SUCCESS';
export const PROJECT_CHANNEL_SAVE_SUCCESS = 'PROJECT_CHANNEL_SAVE_SUCCESS';
export const PROJECT_AUDIO_SAVE_SUCCESS = 'PROJECT_AUDIO_SAVE_SUCCESS';
export const PROJECT_IMAGE_SAVE_SUCCESS = 'PROJECT_IMAGE_SAVE_SUCCESS';
export const PROJECT_FINISHED_SUCCESS = 'PROJECT_FINISHED_SUCCESS';

export const PROJECT_GET_PROJECTINFO_REQUEST='PROJECT_GET_PROJECTINFO_REQUEST';
export const PROJECT_GET_PROJECTINFO_FAILURE='PROJECT_GET_PROJECTINFO_FAILURE';
export const PROJECT_GET_PROJECTINFO_SUCCESS='PROJECT_GET_PROJECTINFO_SUCCESS';

export const PROJECT_SET_STEP_REQUEST='PROJECT_SET_STEP_REQUEST';
export const PROJECT_SET_STEP_FAILURE='PROJECT_SET_STEP_FAILURE';
export const PROJECT_SET_STEP_SUCCESS='PROJECT_SET_STEP_SUCCESS';